import { uniqueString } from "utils";
import avatar from "assets/images/avatar.jpg";
export const onlineUsers = [
  {
    user_id: uniqueString(),
    full_name: "Patrick Hendricks",
    email: "patric@gmail.com",
    profile_pic: avatar,
    created_datetime: "02:50",
    message: "okay sure",
    count: "3",
    status: "online",
  },
  {
    user_id: uniqueString(),
    full_name: "Mark Messer",
    email: "mark@gmail.com",
    profile_pic: avatar,
    created_datetime: "02:50",
    message: "okay sure",
    count: "3",
  },
  {
    user_id: uniqueString(),
    full_name: "Jason",
    email: "jason@gmail.com",
    // profile_pic: avatar,
    created_datetime: "02:50",
    message: "okay sure",
    count: "3",
    status: "away",
  },
  {
    user_id: uniqueString(),
    full_name: "Steve Walker",
    email: "steve@gmail.com",
    // profile_pic: avatar,
    created_datetime: "02:50",
    message: "okay sure",
    count: "3",
    status: "online",
  },
  {
    user_id: uniqueString(),
    full_name: "Albert Rodarte",
    email: "albert@gmail.com",
    profile_pic: avatar,
    created_datetime: "02:50",
    message: "okay sure",
    count: "3",
  },
  {
    user_id: uniqueString(),
    full_name: "Michel",
    email: "michel@gmail.com",
    profile_pic: avatar,
    created_datetime: "02:50",
    message: "okay sure",
    // count: "3",
  },
  {
    user_id: uniqueString(),
    full_name: "Jackson",
    email: "jackson@gmail.com",
    profile_pic: avatar,
    created_datetime: "02:50",
    // message: "okay sure",
    // count: "3",
  },
  {
    user_id: uniqueString(),
    full_name: "Bob",
    email: "bob@gmail.com",
    // profile_pic: avatar,
    created_datetime: "02:50",
    message: "okay sure",
    count: "3",
  },
];
