import {
  RiMessage3Line,
  RiUser2Line,
  RiGroupLine,
  RiPhoneLine,
  RiPhoneFill,
  RiVidiconLine,
  RiVidiconFill,
  RiSearchLine,
  RiMoreFill,
  RiProfileLine,
  RiLogoutCircleRLine,
  RiLock2Line,
  RiMailLine,
  RiUserSharedLine,
  RiMoonLine,
  RiSunLine,
  RiSendPlane2Fill,
  RiAttachmentLine,
  RiImageFill,
  RiEmotionHappyLine,
  RiTimeLine,
  RiCloseFill,
  RiMicFill,
  RiMicOffFill,
  RiQuestionAnswerLine,
  RiCheckLine,
  RiAddFill,
} from "react-icons/ri";
import { BiVideo, BiVideoOff } from "react-icons/bi";
const Icons = {
  add: RiAddFill,
  email: RiMailLine,
  user: RiUser2Line,
  groupUser: RiGroupLine,
  lock: RiLock2Line,
  userEmail: RiUserSharedLine,
  chat: RiMessage3Line,
  emptyChat: RiQuestionAnswerLine,
  phone: RiPhoneLine,
  fillPhone: RiPhoneFill,
  camera: RiVidiconLine,
  videoFillIcon: RiVidiconFill,
  search: RiSearchLine,
  more: RiMoreFill,
  profile: RiProfileLine,
  logout: RiLogoutCircleRLine,
  dark: RiMoonLine,
  light: RiSunLine,
  play: RiSendPlane2Fill,
  attachment: RiAttachmentLine,
  image: RiImageFill,
  happyFace: RiEmotionHappyLine,
  clock: RiTimeLine,
  close: RiCloseFill,
  onmic: RiMicFill,
  offmic: RiMicOffFill,
  oncam: BiVideo,
  offcam: BiVideoOff,
  check: RiCheckLine,
};

export default Icons;
